- name: install python pip and docker
  apt:
    state: latest
    name: ['docker.io','python-pip']

- name: Install docker pip
  pip:
    name:
      - docker
      - requests>=2.20.1
- name: Wordpress Docker Container
  docker_container:
      name: wordpress
      image: wordpress:latest
      detach: True
      published_ports:
      - 8080:80
      env: 
         WORDPRESS_DB_USER={{ mysql_db_user }},
         WORDPRESS_DB_HOST=db.lux.ttu:3306,
         WORDPRESS_DB_PASSWORD={{ mysql_password }},
         WORDPRESS_DB_NAME={{ mysql_db_name }}
      dns_servers:
        - 192.168.56.102
        - 192.168.56.103