---
jobs:
  - name: prometheus
    port: 9999
    targets:
      - prometheus.lux.ttu
  - name: linux
    port: 9100
    targets:
      - infra01.lux.ttu
      - infra02.lux.ttu
  - name: bind
    port: 9119
    targets:
      - ns1.lux.ttu
      - ns2.lux.ttu
  - name: mysqld_exporter
    port: 9104
    targets:
      - infra02.lux.ttu
  - name: haproxy_exporter
    port: 9101
    targets:
      - infra01.lux.ttu