- name: netplan apply
  shell: netplan apply
# - name: dpkg
#   shell: dpkg --configure -a
# - name: systemd-resolved
#   service:
#       name: systemd-resolved
#       state: stopped
#       enabled: no
- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted