---
- name: Create a grafana container
  docker_container:
    name: grafana-server
    image: "grafana/grafana"
    detach: True
    state: started
    published_ports:
      - 3000:3000 
    dns_servers:
      - "{{ master_ip }}"
      - "{{ slave_ip }}"
