---
- name: init
  become: yes
  hosts: nat
  roles:
    - init

- name: bind
  become: yes
  hosts: linux
  roles:
    - bind
  tags: bind

- name: influx
  become: yes
  hosts: vm2
  roles:
    - influxdb
    

- name: grafana
  become: yes
  hosts: yusef
  roles:
    - grafana
  tags: 
    - grafana