---
- name: Initial setup
  hosts: dns
  become: yes
  tasks:
    - name: Setup interface
      template:
        src: templates/enp0s8.j2
        dest: /etc/netplan/55-enp0s8.yaml
      notify:
        - netplan apply
        - resolv.conf fix

    - name: systemd-resolved
      service:
        name: systemd-resolved
        state: stopped
        enabled: no

  handlers:
    - name: netplan apply
      shell: netplan apply
    - name: resolv.conf fix
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf

- name: setup dns
  hosts: dns
  become: yes
  tasks:
    - name: dns package
      apt:
        package: bind9
        update_cache: yes
        state: latest

    - name: config bind
      template:
        src: templates/named.conf.options.j2
        dest: /etc/bind/named.conf.options
      notify:
        - restart bind
        - check conf

    - name: config bind.local
      template:
        src: templates/named.conf.local.j2
        dest: /etc/bind/named.conf.local
      notify:
        - restart bind
        - check conf

    - name: config db
      template:
        src: templates/db.lux.j2
        dest: /etc/bind/db.lux
      when: dns_role == "master"
      notify:
        - bind reload db

    - name: config db ptr
      template:
        src: templates/db.lux.ptr.j2
        dest: /etc/bind/db.lux.ptr
      when: dns_role == "master"
      notify:
        - bind reload db

  handlers:
    - name: check conf
      shell: named-checkconf

    - name: restart bind
      service:
        name: bind9
        state: restarted

    - name: bind reload db
      shell: rndc reload