---
- name: Create User and Group
  hosts: ubuntu
  remote_user: yusef
  become: yes 
  tasks:
    - name: Create group backup
      group:
        name: backup
        state: present
    - name: Create User
      user:
        name: backup
        group: backup
        append: yes
        state: present
        system: yes
    - name: Initialize SSH 
      authorized_key:
        user: backup
        state: present 
        key: "{{ lookup('file', '/Users/YusefWard/.ssh/id_rsa.pub') }}"
    - name: Copy private key 
      copy:
        src: /Users/YusefWard/.ssh/id_rsa
        dest: ~/.ssh/id_rsa
      become_user: backup
    - name: Copy public key
      copy:
        src: /Users/YusefWard/.ssh/id_rsa.pub
        dest: ~/.ssh/id_rsa.pub
      become_user: backup



  