---
- name: Create User and Group
  hosts: 127.0.0.1
  remote_user: yusef
  become: yes 
  tasks:
    - name: Create group backup
      group:
        name: backup
        state: present
    - name: Add user backup to backup
      user:
        name: backup
        groups: sudo, backup
        append: yes
        state: present
        system: yes
        