---
- name: check conf
  shell: named-checkconf

- name: disable systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: 'no'

- name: gather timestamp
  shell: date +%s
  register: tstamp

- name: set up zone database
  template:
    src: "./templates/db.lux.j2"
    dest: "/etc/bind/db.{{zone_name}}"
  when: dns_role == "master"

- name: set up zone PTR database
  template:
    src: "./templates/db.lux.ptr.j2"
    dest: "/etc/bind/db.{{zone_name}}.ptr"
  when: dns_role == "master"

- name: restart bind
  service:
    name: bind9
    state: restarted

- name: reload bind db
  shell: rndc reload

- name: resolveconf fix
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf