---
- name: node_exporter
  hosts: linux
  become: yes
  roles:
    - node_exporter
    - bind

- name: prometheus
  hosts: prometheus
  remote_user: user
  become: yes
  roles:
    - prometheus
    - grafana